# This file generates the GitHub Actions matrix
---
include:
  # totem
  - board: nice_nano_v2
    shield: totem_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: totem_central_dongle
  - board: seeeduino_xiao_ble
    shield: totem_central_left
    artifact-name: totem_central_left
  - board: seeeduino_xiao_ble
    shield: totem_peripheral_left
    artifact-name: totem_peripheral_left
  - board: seeeduino_xiao_ble
    shield: totem_peripheral_right
    artifact-name: totem_peripheral_right
    
  # reset
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
